apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthapp-deploy
  labels:
    app: healthapp-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthapp-app
  template:
    metadata:
      labels:
        app: healthapp-app
    spec:
      containers:
      - name: healthapp-container
        image: dhakshana1197/healthapp-app
        ports:
        - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: healthapp-np-service
  labels:
    app: healthapp-app
spec:
  selector:
    app: healthapp-app

  type: NodePort
  ports:
  - nodePort: 31001    
    port: 8087
    targetPort: 8087
